import type { ClientGuideDef } from '../types';
import { CLASH_VERGE_GUIDE_SOURCE_URL, CLASH_VERGE_SCREENSHOTS } from '../../SubscriptionTabData';

export const clashVergeGuide: ClientGuideDef = {
  byPlatform: {
    windows: {
      recommendedFormat: 'clash',
      noteKey: 'guides.clashVerge.windows.note',
      sourceLabelKey: 'guides.clashVerge.windows.sourceLabel',
      sourceUrl: CLASH_VERGE_GUIDE_SOURCE_URL,
      steps: [
        {
          tone: 'launch',
          titleKey: 'guides.clashVerge.windows.step0.title',
          descriptionKey: 'guides.clashVerge.windows.step0.description',
          helperKey: 'guides.clashVerge.windows.step0.helper',
          visualLabel: 'Profiles',
          visualItemsKey: 'guides.clashVerge.windows.step0.visualItems',
          ctaLabelKey: 'guides.clashVerge.windows.step0.ctaLabel',
          screenshot: {
            src: CLASH_VERGE_SCREENSHOTS.profilesEmpty,
            altKey: 'guides.clashVerge.windows.step0.screenshotAlt',
          },
        },
        {
          tone: 'import',
          titleKey: 'guides.clashVerge.windows.step1.title',
          descriptionKey: 'guides.clashVerge.windows.step1.description',
          helperKey: 'guides.clashVerge.windows.step1.helper',
          visualLabel: 'Create profile',
          visualItemsKey: 'guides.clashVerge.windows.step1.visualItems',
          ctaLabelKey: 'guides.clashVerge.windows.step1.ctaLabel',
          screenshot: {
            src: CLASH_VERGE_SCREENSHOTS.createProfile,
            altKey: 'guides.clashVerge.windows.step1.screenshotAlt',
          },
        },
        {
          tone: 'import',
          titleKey: 'guides.clashVerge.windows.step2.title',
          descriptionKey: 'guides.clashVerge.windows.step2.description',
          helperKey: 'guides.clashVerge.windows.step2.helper',
          visualLabel: 'Subscription URL',
          visualItemsKey: 'guides.clashVerge.windows.step2.visualItems',
          ctaLabelKey: 'guides.clashVerge.windows.step2.ctaLabel',
          screenshot: {
            src: CLASH_VERGE_SCREENSHOTS.pasteSubscription,
            altKey: 'guides.clashVerge.windows.step2.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.clashVerge.windows.step3.title',
          descriptionKey: 'guides.clashVerge.windows.step3.description',
          helperKey: 'guides.clashVerge.windows.step3.helper',
          visualLabel: 'Profile card',
          visualItemsKey: 'guides.clashVerge.windows.step3.visualItems',
          ctaLabelKey: 'guides.clashVerge.windows.step3.ctaLabel',
          screenshot: {
            src: CLASH_VERGE_SCREENSHOTS.subscriptionAdded,
            altKey: 'guides.clashVerge.windows.step3.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.clashVerge.windows.step4.title',
          descriptionKey: 'guides.clashVerge.windows.step4.description',
          helperKey: 'guides.clashVerge.windows.step4.helper',
          visualLabel: 'Proxy groups',
          visualItemsKey: 'guides.clashVerge.windows.step4.visualItems',
          ctaLabelKey: 'guides.clashVerge.windows.step4.ctaLabel',
          screenshot: {
            src: CLASH_VERGE_SCREENSHOTS.proxyGroups,
            altKey: 'guides.clashVerge.windows.step4.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.clashVerge.windows.step5.title',
          descriptionKey: 'guides.clashVerge.windows.step5.description',
          helperKey: 'guides.clashVerge.windows.step5.helper',
          visualLabel: 'System proxy',
          visualItemsKey: 'guides.clashVerge.windows.step5.visualItems',
          ctaLabelKey: 'guides.clashVerge.windows.step5.ctaLabel',
          screenshot: {
            src: CLASH_VERGE_SCREENSHOTS.systemProxy,
            altKey: 'guides.clashVerge.windows.step5.screenshotAlt',
          },
        },
      ],
    },
    macos: {
      recommendedFormat: 'clash',
      noteKey: 'guides.clashVerge.macos.note',
      sourceLabelKey: 'guides.clashVerge.macos.sourceLabel',
      sourceUrl: CLASH_VERGE_GUIDE_SOURCE_URL,
      steps: [
        {
          tone: 'launch',
          titleKey: 'guides.clashVerge.macos.step0.title',
          descriptionKey: 'guides.clashVerge.macos.step0.description',
          helperKey: 'guides.clashVerge.macos.step0.helper',
          visualLabel: 'Profiles',
          visualItemsKey: 'guides.clashVerge.macos.step0.visualItems',
          ctaLabelKey: 'guides.clashVerge.macos.step0.ctaLabel',
          screenshot: {
            src: CLASH_VERGE_SCREENSHOTS.profilesEmpty,
            altKey: 'guides.clashVerge.macos.step0.screenshotAlt',
          },
        },
        {
          tone: 'import',
          titleKey: 'guides.clashVerge.macos.step1.title',
          descriptionKey: 'guides.clashVerge.macos.step1.description',
          helperKey: 'guides.clashVerge.macos.step1.helper',
          visualLabel: 'Create profile',
          visualItemsKey: 'guides.clashVerge.macos.step1.visualItems',
          ctaLabelKey: 'guides.clashVerge.macos.step1.ctaLabel',
          screenshot: {
            src: CLASH_VERGE_SCREENSHOTS.createProfile,
            altKey: 'guides.clashVerge.macos.step1.screenshotAlt',
          },
        },
        {
          tone: 'import',
          titleKey: 'guides.clashVerge.macos.step2.title',
          descriptionKey: 'guides.clashVerge.macos.step2.description',
          helperKey: 'guides.clashVerge.macos.step2.helper',
          visualLabel: 'Subscription URL',
          visualItemsKey: 'guides.clashVerge.macos.step2.visualItems',
          ctaLabelKey: 'guides.clashVerge.macos.step2.ctaLabel',
          screenshot: {
            src: CLASH_VERGE_SCREENSHOTS.pasteSubscription,
            altKey: 'guides.clashVerge.macos.step2.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.clashVerge.macos.step3.title',
          descriptionKey: 'guides.clashVerge.macos.step3.description',
          helperKey: 'guides.clashVerge.macos.step3.helper',
          visualLabel: 'Profile card',
          visualItemsKey: 'guides.clashVerge.macos.step3.visualItems',
          ctaLabelKey: 'guides.clashVerge.macos.step3.ctaLabel',
          screenshot: {
            src: CLASH_VERGE_SCREENSHOTS.subscriptionAdded,
            altKey: 'guides.clashVerge.macos.step3.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.clashVerge.macos.step4.title',
          descriptionKey: 'guides.clashVerge.macos.step4.description',
          helperKey: 'guides.clashVerge.macos.step4.helper',
          visualLabel: 'Proxy groups',
          visualItemsKey: 'guides.clashVerge.macos.step4.visualItems',
          ctaLabelKey: 'guides.clashVerge.macos.step4.ctaLabel',
          screenshot: {
            src: CLASH_VERGE_SCREENSHOTS.proxyGroups,
            altKey: 'guides.clashVerge.macos.step4.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.clashVerge.macos.step5.title',
          descriptionKey: 'guides.clashVerge.macos.step5.description',
          helperKey: 'guides.clashVerge.macos.step5.helper',
          visualLabel: 'System proxy',
          visualItemsKey: 'guides.clashVerge.macos.step5.visualItems',
          ctaLabelKey: 'guides.clashVerge.macos.step5.ctaLabel',
          screenshot: {
            src: CLASH_VERGE_SCREENSHOTS.systemProxy,
            altKey: 'guides.clashVerge.macos.step5.screenshotAlt',
          },
        },
      ],
    },
    linux: {
      recommendedFormat: 'clash',
      noteKey: 'guides.clashVerge.linux.note',
      steps: [
        {
          tone: 'launch',
          titleKey: 'guides.clashVerge.linux.step0.title',
          descriptionKey: 'guides.clashVerge.linux.step0.description',
          helperKey: 'guides.clashVerge.linux.step0.helper',
          visualLabel: 'Profiles',
          visualItemsKey: 'guides.clashVerge.linux.step0.visualItems',
          ctaLabelKey: 'guides.clashVerge.linux.step0.ctaLabel',
        },
        {
          tone: 'import',
          titleKey: 'guides.clashVerge.linux.step1.title',
          descriptionKey: 'guides.clashVerge.linux.step1.description',
          helperKey: 'guides.clashVerge.linux.step1.helper',
          visualLabel: 'Import from URL',
          visualItemsKey: 'guides.clashVerge.linux.step1.visualItems',
          ctaLabelKey: 'guides.clashVerge.linux.step1.ctaLabel',
        },
        {
          tone: 'connect',
          titleKey: 'guides.clashVerge.linux.step2.title',
          descriptionKey: 'guides.clashVerge.linux.step2.description',
          helperKey: 'guides.clashVerge.linux.step2.helper',
          visualLabel: 'Proxy / TUN',
          visualItemsKey: 'guides.clashVerge.linux.step2.visualItems',
          ctaLabelKey: 'guides.clashVerge.linux.step2.ctaLabel',
        },
      ],
    },
  },
};
