import type { ClientGuideDef } from '../types';
import {
  FLCLASH_GUIDE_SOURCE_URL,
  FLCLASH_MACOS_GUIDE_SOURCE_URL,
  FLCLASH_ANDROID_GUIDE_SOURCE_URL,
  FLCLASH_SCREENSHOTS,
  FLCLASH_MACOS_SCREENSHOTS,
  FLCLASH_ANDROID_SCREENSHOTS,
} from '../../SubscriptionTabData';

export const flClashGuide: ClientGuideDef = {
  byPlatform: {
    windows: {
      recommendedFormat: 'clash',
      noteKey: 'guides.flClash.windows.note',
      sourceLabelKey: 'guides.flClash.windows.sourceLabel',
      sourceUrl: FLCLASH_GUIDE_SOURCE_URL,
      steps: [
        {
          tone: 'launch',
          titleKey: 'guides.flClash.windows.step0.title',
          descriptionKey: 'guides.flClash.windows.step0.description',
          helperKey: 'guides.flClash.windows.step0.helper',
          visualLabel: 'Config screen',
          visualLabelKey: 'guides.flClash.windows.step0.visualLabel',
          visualItemsKey: 'guides.flClash.windows.step0.visualItems',
          ctaLabelKey: 'guides.flClash.windows.step0.ctaLabel',
          screenshot: {
            src: FLCLASH_SCREENSHOTS.newConfiguration,
            altKey: 'guides.flClash.windows.step0.screenshotAlt',
          },
        },
        {
          tone: 'import',
          titleKey: 'guides.flClash.windows.step1.title',
          descriptionKey: 'guides.flClash.windows.step1.description',
          helperKey: 'guides.flClash.windows.step1.helper',
          visualLabel: 'URL import',
          visualLabelKey: 'guides.flClash.windows.step1.visualLabel',
          visualItemsKey: 'guides.flClash.windows.step1.visualItems',
          ctaLabelKey: 'guides.flClash.windows.step1.ctaLabel',
          screenshot: {
            src: FLCLASH_SCREENSHOTS.url,
            altKey: 'guides.flClash.windows.step1.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.flClash.windows.step2.title',
          descriptionKey: 'guides.flClash.windows.step2.description',
          helperKey: 'guides.flClash.windows.step2.helper',
          visualLabel: 'Profile card',
          visualLabelKey: 'guides.flClash.windows.step2.visualLabel',
          visualItemsKey: 'guides.flClash.windows.step2.visualItems',
          ctaLabelKey: 'guides.flClash.windows.step2.ctaLabel',
          screenshot: {
            src: FLCLASH_SCREENSHOTS.editConfiguration,
            altKey: 'guides.flClash.windows.step2.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.flClash.windows.step3.title',
          descriptionKey: 'guides.flClash.windows.step3.description',
          helperKey: 'guides.flClash.windows.step3.helper',
          visualLabel: 'Node selection',
          visualLabelKey: 'guides.flClash.windows.step3.visualLabel',
          visualItemsKey: 'guides.flClash.windows.step3.visualItems',
          ctaLabelKey: 'guides.flClash.windows.step3.ctaLabel',
          screenshot: {
            src: FLCLASH_SCREENSHOTS.nodeSelection,
            altKey: 'guides.flClash.windows.step3.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.flClash.windows.step4.title',
          descriptionKey: 'guides.flClash.windows.step4.description',
          helperKey: 'guides.flClash.windows.step4.helper',
          visualLabel: 'Connect',
          visualLabelKey: 'guides.flClash.windows.step4.visualLabel',
          visualItemsKey: 'guides.flClash.windows.step4.visualItems',
          ctaLabelKey: 'guides.flClash.windows.step4.ctaLabel',
          screenshot: {
            src: FLCLASH_SCREENSHOTS.enableProxy,
            altKey: 'guides.flClash.windows.step4.screenshotAlt',
          },
        },
      ],
    },
    macos: {
      recommendedFormat: 'clash',
      noteKey: 'guides.flClash.macos.note',
      sourceLabelKey: 'guides.flClash.macos.sourceLabel',
      sourceUrl: FLCLASH_MACOS_GUIDE_SOURCE_URL,
      steps: [
        {
          tone: 'launch',
          titleKey: 'guides.flClash.macos.step0.title',
          descriptionKey: 'guides.flClash.macos.step0.description',
          helperKey: 'guides.flClash.macos.step0.helper',
          visualLabel: 'Main screen',
          visualLabelKey: 'guides.flClash.macos.step0.visualLabel',
          visualItemsKey: 'guides.flClash.macos.step0.visualItems',
          ctaLabelKey: 'guides.flClash.macos.step0.ctaLabel',
          screenshot: {
            src: FLCLASH_MACOS_SCREENSHOTS.main,
            altKey: 'guides.flClash.macos.step0.screenshotAlt',
          },
        },
        {
          tone: 'import',
          titleKey: 'guides.flClash.macos.step1.title',
          descriptionKey: 'guides.flClash.macos.step1.description',
          helperKey: 'guides.flClash.macos.step1.helper',
          visualLabel: 'Config import',
          visualLabelKey: 'guides.flClash.macos.step1.visualLabel',
          visualItemsKey: 'guides.flClash.macos.step1.visualItems',
          ctaLabelKey: 'guides.flClash.macos.step1.ctaLabel',
          screenshot: {
            src: FLCLASH_MACOS_SCREENSHOTS.config,
            altKey: 'guides.flClash.macos.step1.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.flClash.macos.step2.title',
          descriptionKey: 'guides.flClash.macos.step2.description',
          helperKey: 'guides.flClash.macos.step2.helper',
          visualLabel: 'Node selection',
          visualLabelKey: 'guides.flClash.macos.step2.visualLabel',
          visualItemsKey: 'guides.flClash.macos.step2.visualItems',
          ctaLabelKey: 'guides.flClash.macos.step2.ctaLabel',
          screenshot: {
            src: FLCLASH_MACOS_SCREENSHOTS.chooseProxy,
            altKey: 'guides.flClash.macos.step2.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.flClash.macos.step3.title',
          descriptionKey: 'guides.flClash.macos.step3.description',
          helperKey: 'guides.flClash.macos.step3.helper',
          visualLabel: 'Connect',
          visualLabelKey: 'guides.flClash.macos.step3.visualLabel',
          visualItemsKey: 'guides.flClash.macos.step3.visualItems',
          ctaLabelKey: 'guides.flClash.macos.step3.ctaLabel',
          screenshot: {
            src: FLCLASH_MACOS_SCREENSHOTS.startProxy,
            altKey: 'guides.flClash.macos.step3.screenshotAlt',
          },
        },
      ],
    },
    linux: {
      recommendedFormat: 'clash',
      noteKey: 'guides.flClash.linux.note',
      sourceLabelKey: 'guides.flClash.linux.sourceLabel',
      sourceUrl: FLCLASH_GUIDE_SOURCE_URL,
      steps: [
        {
          tone: 'launch',
          titleKey: 'guides.flClash.linux.step0.title',
          descriptionKey: 'guides.flClash.linux.step0.description',
          helperKey: 'guides.flClash.linux.step0.helper',
          visualLabel: 'Config screen',
          visualLabelKey: 'guides.flClash.linux.step0.visualLabel',
          visualItemsKey: 'guides.flClash.linux.step0.visualItems',
          ctaLabelKey: 'guides.flClash.linux.step0.ctaLabel',
          screenshot: {
            src: FLCLASH_SCREENSHOTS.newConfiguration,
            altKey: 'guides.flClash.linux.step0.screenshotAlt',
          },
        },
        {
          tone: 'import',
          titleKey: 'guides.flClash.linux.step1.title',
          descriptionKey: 'guides.flClash.linux.step1.description',
          helperKey: 'guides.flClash.linux.step1.helper',
          visualLabel: 'URL import',
          visualLabelKey: 'guides.flClash.linux.step1.visualLabel',
          visualItemsKey: 'guides.flClash.linux.step1.visualItems',
          ctaLabelKey: 'guides.flClash.linux.step1.ctaLabel',
          screenshot: {
            src: FLCLASH_SCREENSHOTS.url,
            altKey: 'guides.flClash.linux.step1.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.flClash.linux.step2.title',
          descriptionKey: 'guides.flClash.linux.step2.description',
          helperKey: 'guides.flClash.linux.step2.helper',
          visualLabel: 'Profile card',
          visualLabelKey: 'guides.flClash.linux.step2.visualLabel',
          visualItemsKey: 'guides.flClash.linux.step2.visualItems',
          ctaLabelKey: 'guides.flClash.linux.step2.ctaLabel',
          screenshot: {
            src: FLCLASH_SCREENSHOTS.editConfiguration,
            altKey: 'guides.flClash.linux.step2.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.flClash.linux.step3.title',
          descriptionKey: 'guides.flClash.linux.step3.description',
          helperKey: 'guides.flClash.linux.step3.helper',
          visualLabel: 'Node selection',
          visualLabelKey: 'guides.flClash.linux.step3.visualLabel',
          visualItemsKey: 'guides.flClash.linux.step3.visualItems',
          ctaLabelKey: 'guides.flClash.linux.step3.ctaLabel',
          screenshot: {
            src: FLCLASH_SCREENSHOTS.nodeSelection,
            altKey: 'guides.flClash.linux.step3.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.flClash.linux.step4.title',
          descriptionKey: 'guides.flClash.linux.step4.description',
          helperKey: 'guides.flClash.linux.step4.helper',
          visualLabel: 'Connect',
          visualLabelKey: 'guides.flClash.linux.step4.visualLabel',
          visualItemsKey: 'guides.flClash.linux.step4.visualItems',
          ctaLabelKey: 'guides.flClash.linux.step4.ctaLabel',
          screenshot: {
            src: FLCLASH_SCREENSHOTS.enableProxy,
            altKey: 'guides.flClash.linux.step4.screenshotAlt',
          },
        },
      ],
    },
    android: {
      recommendedFormat: 'clash',
      noteKey: 'guides.flClash.android.note',
      sourceLabelKey: 'guides.flClash.android.sourceLabel',
      sourceUrl: FLCLASH_ANDROID_GUIDE_SOURCE_URL,
      steps: [
        {
          tone: 'launch',
          titleKey: 'guides.flClash.android.step0.title',
          descriptionKey: 'guides.flClash.android.step0.description',
          helperKey: 'guides.flClash.android.step0.helper',
          visualLabel: 'Config entry',
          visualLabelKey: 'guides.flClash.android.step0.visualLabel',
          visualItemsKey: 'guides.flClash.android.step0.visualItems',
          ctaLabelKey: 'guides.flClash.android.step0.ctaLabel',
          screenshot: {
            src: FLCLASH_ANDROID_SCREENSHOTS.import,
            altKey: 'guides.flClash.android.step0.screenshotAlt',
          },
        },
        {
          tone: 'import',
          titleKey: 'guides.flClash.android.step1.title',
          descriptionKey: 'guides.flClash.android.step1.description',
          helperKey: 'guides.flClash.android.step1.helper',
          visualLabel: 'URL import',
          visualLabelKey: 'guides.flClash.android.step1.visualLabel',
          visualItemsKey: 'guides.flClash.android.step1.visualItems',
          ctaLabelKey: 'guides.flClash.android.step1.ctaLabel',
          screenshot: {
            src: FLCLASH_ANDROID_SCREENSHOTS.import,
            altKey: 'guides.flClash.android.step1.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.flClash.android.step2.title',
          descriptionKey: 'guides.flClash.android.step2.description',
          helperKey: 'guides.flClash.android.step2.helper',
          visualLabel: 'Node selection',
          visualLabelKey: 'guides.flClash.android.step2.visualLabel',
          visualItemsKey: 'guides.flClash.android.step2.visualItems',
          ctaLabelKey: 'guides.flClash.android.step2.ctaLabel',
          screenshot: {
            src: FLCLASH_ANDROID_SCREENSHOTS.connect,
            altKey: 'guides.flClash.android.step2.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.flClash.android.step3.title',
          descriptionKey: 'guides.flClash.android.step3.description',
          helperKey: 'guides.flClash.android.step3.helper',
          visualLabel: 'Connect',
          visualLabelKey: 'guides.flClash.android.step3.visualLabel',
          visualItemsKey: 'guides.flClash.android.step3.visualItems',
          ctaLabelKey: 'guides.flClash.android.step3.ctaLabel',
          screenshot: {
            src: FLCLASH_ANDROID_SCREENSHOTS.connect,
            altKey: 'guides.flClash.android.step3.screenshotAlt',
          },
        },
      ],
    },
  },
};
