import type { ClientGuideDef } from '../types';
import {
  SINGBOX_APPLE_GUIDE_SOURCE_URL,
  SINGBOX_APPLE_SCREENSHOTS,
  SINGBOX_ANDROID_GUIDE_SOURCE_URL,
  SINGBOX_ANDROID_SCREENSHOTS,
} from '../../SubscriptionTabData';

export const singBoxGuide: ClientGuideDef = {
  byPlatform: {
    android: {
      recommendedFormat: 'singbox',
      noteKey: 'guides.singBox.android.note',
      sourceLabelKey: 'guides.singBox.android.sourceLabel',
      sourceUrl: SINGBOX_ANDROID_GUIDE_SOURCE_URL,
      steps: [
        {
          tone: 'launch',
          titleKey: 'guides.singBox.android.step0.title',
          descriptionKey: 'guides.singBox.android.step0.description',
          helperKey: 'guides.singBox.android.step0.helper',
          visualLabel: 'New profile',
          visualLabelKey: 'guides.singBox.android.step0.visualLabel',
          visualItemsKey: 'guides.singBox.android.step0.visualItems',
          ctaLabelKey: 'guides.singBox.android.step0.ctaLabel',
          screenshot: {
            src: SINGBOX_ANDROID_SCREENSHOTS.createConfig1,
            altKey: 'guides.singBox.android.step0.screenshotAlt',
          },
        },
        {
          tone: 'import',
          titleKey: 'guides.singBox.android.step1.title',
          descriptionKey: 'guides.singBox.android.step1.description',
          helperKey: 'guides.singBox.android.step1.helper',
          visualLabel: 'Import method',
          visualLabelKey: 'guides.singBox.android.step1.visualLabel',
          visualItemsKey: 'guides.singBox.android.step1.visualItems',
          ctaLabelKey: 'guides.singBox.android.step1.ctaLabel',
          screenshot: {
            src: SINGBOX_ANDROID_SCREENSHOTS.createConfig2,
            altKey: 'guides.singBox.android.step1.screenshotAlt',
          },
        },
        {
          tone: 'import',
          titleKey: 'guides.singBox.android.step2.title',
          descriptionKey: 'guides.singBox.android.step2.description',
          helperKey: 'guides.singBox.android.step2.helper',
          visualLabel: 'Profile settings',
          visualLabelKey: 'guides.singBox.android.step2.visualLabel',
          visualItemsKey: 'guides.singBox.android.step2.visualItems',
          ctaLabelKey: 'guides.singBox.android.step2.ctaLabel',
          screenshot: {
            src: SINGBOX_ANDROID_SCREENSHOTS.configSettings,
            altKey: 'guides.singBox.android.step2.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.singBox.android.step3.title',
          descriptionKey: 'guides.singBox.android.step3.description',
          helperKey: 'guides.singBox.android.step3.helper',
          visualLabel: 'VPN permission',
          visualLabelKey: 'guides.singBox.android.step3.visualLabel',
          visualItemsKey: 'guides.singBox.android.step3.visualItems',
          ctaLabelKey: 'guides.singBox.android.step3.ctaLabel',
          screenshot: {
            src: SINGBOX_ANDROID_SCREENSHOTS.vpnPermission,
            altKey: 'guides.singBox.android.step3.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.singBox.android.step4.title',
          descriptionKey: 'guides.singBox.android.step4.description',
          helperKey: 'guides.singBox.android.step4.helper',
          visualLabel: 'Node selection',
          visualLabelKey: 'guides.singBox.android.step4.visualLabel',
          visualItemsKey: 'guides.singBox.android.step4.visualItems',
          ctaLabelKey: 'guides.singBox.android.step4.ctaLabel',
          screenshot: {
            src: SINGBOX_ANDROID_SCREENSHOTS.nodeSelection,
            altKey: 'guides.singBox.android.step4.screenshotAlt',
          },
        },
      ],
    },
    ios: {
      recommendedFormat: 'singbox',
      noteKey: 'guides.singBox.ios.note',
      sourceLabelKey: 'guides.singBox.ios.sourceLabel',
      sourceUrl: SINGBOX_APPLE_GUIDE_SOURCE_URL,
      steps: [
        {
          tone: 'launch',
          titleKey: 'guides.singBox.ios.step0.title',
          descriptionKey: 'guides.singBox.ios.step0.description',
          helperKey: 'guides.singBox.ios.step0.helper',
          visualLabel: 'Configuration screen',
          visualLabelKey: 'guides.singBox.ios.step0.visualLabel',
          visualItemsKey: 'guides.singBox.ios.step0.visualItems',
          ctaLabelKey: 'guides.singBox.ios.step0.ctaLabel',
          screenshot: {
            src: SINGBOX_APPLE_SCREENSHOTS.iosConfigurationSettings1,
            altKey: 'guides.singBox.ios.step0.screenshotAlt',
          },
        },
        {
          tone: 'import',
          titleKey: 'guides.singBox.ios.step1.title',
          descriptionKey: 'guides.singBox.ios.step1.description',
          helperKey: 'guides.singBox.ios.step1.helper',
          visualLabel: 'Import profile',
          visualLabelKey: 'guides.singBox.ios.step1.visualLabel',
          visualItemsKey: 'guides.singBox.ios.step1.visualItems',
          ctaLabelKey: 'guides.singBox.ios.step1.ctaLabel',
          screenshot: {
            src: SINGBOX_APPLE_SCREENSHOTS.iosConfigurationSettings2,
            altKey: 'guides.singBox.ios.step1.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.singBox.ios.step2.title',
          descriptionKey: 'guides.singBox.ios.step2.description',
          helperKey: 'guides.singBox.ios.step2.helper',
          visualLabel: 'Enable profile',
          visualLabelKey: 'guides.singBox.ios.step2.visualLabel',
          visualItemsKey: 'guides.singBox.ios.step2.visualItems',
          ctaLabelKey: 'guides.singBox.ios.step2.ctaLabel',
          screenshot: {
            src: SINGBOX_APPLE_SCREENSHOTS.iosEnableSingBox1,
            altKey: 'guides.singBox.ios.step2.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.singBox.ios.step3.title',
          descriptionKey: 'guides.singBox.ios.step3.description',
          helperKey: 'guides.singBox.ios.step3.helper',
          visualLabel: 'System permission',
          visualLabelKey: 'guides.singBox.ios.step3.visualLabel',
          visualItemsKey: 'guides.singBox.ios.step3.visualItems',
          ctaLabelKey: 'guides.singBox.ios.step3.ctaLabel',
          screenshot: {
            src: SINGBOX_APPLE_SCREENSHOTS.iosEnableSingBox2,
            altKey: 'guides.singBox.ios.step3.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.singBox.ios.step4.title',
          descriptionKey: 'guides.singBox.ios.step4.description',
          helperKey: 'guides.singBox.ios.step4.helper',
          visualLabel: 'Groups',
          visualLabelKey: 'guides.singBox.ios.step4.visualLabel',
          visualItemsKey: 'guides.singBox.ios.step4.visualItems',
          ctaLabelKey: 'guides.singBox.ios.step4.ctaLabel',
          screenshot: {
            src: SINGBOX_APPLE_SCREENSHOTS.iosGroups,
            altKey: 'guides.singBox.ios.step4.screenshotAlt',
          },
        },
      ],
    },
    macos: {
      recommendedFormat: 'singbox',
      noteKey: 'guides.singBox.macos.note',
      sourceLabelKey: 'guides.singBox.macos.sourceLabel',
      sourceUrl: SINGBOX_APPLE_GUIDE_SOURCE_URL,
      steps: [
        {
          tone: 'launch',
          titleKey: 'guides.singBox.macos.step0.title',
          descriptionKey: 'guides.singBox.macos.step0.description',
          helperKey: 'guides.singBox.macos.step0.helper',
          visualLabel: 'Profile screen',
          visualLabelKey: 'guides.singBox.macos.step0.visualLabel',
          visualItemsKey: 'guides.singBox.macos.step0.visualItems',
          ctaLabelKey: 'guides.singBox.macos.step0.ctaLabel',
          screenshot: {
            src: SINGBOX_APPLE_SCREENSHOTS.macosConfigurationSettings,
            altKey: 'guides.singBox.macos.step0.screenshotAlt',
          },
        },
        {
          tone: 'import',
          titleKey: 'guides.singBox.macos.step1.title',
          descriptionKey: 'guides.singBox.macos.step1.description',
          helperKey: 'guides.singBox.macos.step1.helper',
          visualLabel: 'Profile import',
          visualLabelKey: 'guides.singBox.macos.step1.visualLabel',
          visualItemsKey: 'guides.singBox.macos.step1.visualItems',
          ctaLabelKey: 'guides.singBox.macos.step1.ctaLabel',
          screenshot: {
            src: SINGBOX_APPLE_SCREENSHOTS.macosEnableSingBox,
            altKey: 'guides.singBox.macos.step1.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.singBox.macos.step2.title',
          descriptionKey: 'guides.singBox.macos.step2.description',
          helperKey: 'guides.singBox.macos.step2.helper',
          visualLabel: 'Network mode',
          visualLabelKey: 'guides.singBox.macos.step2.visualLabel',
          visualItemsKey: 'guides.singBox.macos.step2.visualItems',
          ctaLabelKey: 'guides.singBox.macos.step2.ctaLabel',
          screenshot: {
            src: SINGBOX_APPLE_SCREENSHOTS.macosInternetMode,
            altKey: 'guides.singBox.macos.step2.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.singBox.macos.step3.title',
          descriptionKey: 'guides.singBox.macos.step3.description',
          helperKey: 'guides.singBox.macos.step3.helper',
          visualLabel: 'Node selection',
          visualLabelKey: 'guides.singBox.macos.step3.visualLabel',
          visualItemsKey: 'guides.singBox.macos.step3.visualItems',
          ctaLabelKey: 'guides.singBox.macos.step3.ctaLabel',
          screenshot: {
            src: SINGBOX_APPLE_SCREENSHOTS.macosNodeSelection,
            altKey: 'guides.singBox.macos.step3.screenshotAlt',
          },
        },
      ],
    },
    linux: {
      recommendedFormat: 'singbox',
      noteKey: 'guides.singBox.linux.note',
      steps: [
        {
          tone: 'launch',
          titleKey: 'guides.singBox.linux.step0.title',
          descriptionKey: 'guides.singBox.linux.step0.description',
          helperKey: 'guides.singBox.linux.step0.helper',
          visualLabel: 'Profiles / Servers',
          visualItemsKey: 'guides.singBox.linux.step0.visualItems',
          ctaLabelKey: 'guides.singBox.linux.step0.ctaLabel',
        },
        {
          tone: 'import',
          titleKey: 'guides.singBox.linux.step1.title',
          descriptionKey: 'guides.singBox.linux.step1.description',
          helperKey: 'guides.singBox.linux.step1.helper',
          visualLabel: 'Import Sing-box profile',
          visualItemsKey: 'guides.singBox.linux.step1.visualItems',
          ctaLabelKey: 'guides.singBox.linux.step1.ctaLabel',
        },
        {
          tone: 'connect',
          titleKey: 'guides.singBox.linux.step2.title',
          descriptionKey: 'guides.singBox.linux.step2.description',
          helperKey: 'guides.singBox.linux.step2.helper',
          visualLabel: 'Connect',
          visualItemsKey: 'guides.singBox.linux.step2.visualItems',
          ctaLabelKey: 'guides.singBox.linux.step2.ctaLabel',
        },
      ],
    },
  },
};
