import type { ClientGuideDef } from '../types';
import {
  SPARKLE_OFFICIAL_ISSUES_SOURCE_URL,
  SPARKLE_WINDOWS_SCREENSHOTS,
} from '../../SubscriptionTabData';

export const sparkleGuide: ClientGuideDef = {
  byPlatform: {
    windows: {
      recommendedFormat: 'clash',
      noteKey: 'guides.sparkle.windows.note',
      sourceLabelKey: 'guides.sparkle.windows.sourceLabel',
      sourceUrl: SPARKLE_OFFICIAL_ISSUES_SOURCE_URL,
      steps: [
        {
          tone: 'launch',
          titleKey: 'guides.sparkle.windows.step0.title',
          descriptionKey: 'guides.sparkle.windows.step0.description',
          helperKey: 'guides.sparkle.windows.step0.helper',
          visualLabel: 'Subscription management',
          visualLabelKey: 'guides.sparkle.windows.step0.visualLabel',
          visualItemsKey: 'guides.sparkle.windows.step0.visualItems',
          ctaLabelKey: 'guides.sparkle.windows.step0.ctaLabel',
          screenshot: {
            src: SPARKLE_WINDOWS_SCREENSHOTS.subscriptionManagement,
            altKey: 'guides.sparkle.windows.step0.screenshotAlt',
          },
        },
        {
          tone: 'import',
          titleKey: 'guides.sparkle.windows.step1.title',
          descriptionKey: 'guides.sparkle.windows.step1.description',
          helperKey: 'guides.sparkle.windows.step1.helper',
          visualLabel: 'Import menu',
          visualLabelKey: 'guides.sparkle.windows.step1.visualLabel',
          visualItemsKey: 'guides.sparkle.windows.step1.visualItems',
          ctaLabelKey: 'guides.sparkle.windows.step1.ctaLabel',
          screenshot: {
            src: SPARKLE_WINDOWS_SCREENSHOTS.importMenu,
            altKey: 'guides.sparkle.windows.step1.screenshotAlt',
          },
        },
        {
          tone: 'import',
          titleKey: 'guides.sparkle.windows.step2.title',
          descriptionKey: 'guides.sparkle.windows.step2.description',
          helperKey: 'guides.sparkle.windows.step2.helper',
          visualLabel: 'Remote config URL',
          visualLabelKey: 'guides.sparkle.windows.step2.visualLabel',
          visualItemsKey: 'guides.sparkle.windows.step2.visualItems',
          ctaLabelKey: 'guides.sparkle.windows.step2.ctaLabel',
          screenshot: {
            src: SPARKLE_WINDOWS_SCREENSHOTS.remoteConfigUrl,
            altKey: 'guides.sparkle.windows.step2.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.sparkle.windows.step3.title',
          descriptionKey: 'guides.sparkle.windows.step3.description',
          helperKey: 'guides.sparkle.windows.step3.helper',
          visualLabel: 'System proxy',
          visualLabelKey: 'guides.sparkle.windows.step3.visualLabel',
          visualItemsKey: 'guides.sparkle.windows.step3.visualItems',
          ctaLabelKey: 'guides.sparkle.windows.step3.ctaLabel',
          screenshot: {
            src: SPARKLE_WINDOWS_SCREENSHOTS.systemProxy,
            altKey: 'guides.sparkle.windows.step3.screenshotAlt',
          },
        },
      ],
    },
    macos: {
      recommendedFormat: 'clash',
      noteKey: 'guides.sparkle.macos.note',
      steps: [
        {
          tone: 'launch',
          titleKey: 'guides.sparkle.macos.step0.title',
          descriptionKey: 'guides.sparkle.macos.step0.description',
          helperKey: 'guides.sparkle.macos.step0.helper',
          visualLabel: 'Subscription entry',
          visualLabelKey: 'guides.sparkle.macos.step0.visualLabel',
          visualItemsKey: 'guides.sparkle.macos.step0.visualItems',
          ctaLabelKey: 'guides.sparkle.macos.step0.ctaLabel',
        },
        {
          tone: 'import',
          titleKey: 'guides.sparkle.macos.step1.title',
          descriptionKey: 'guides.sparkle.macos.step1.description',
          helperKey: 'guides.sparkle.macos.step1.helper',
          visualLabel: 'Remote import',
          visualLabelKey: 'guides.sparkle.macos.step1.visualLabel',
          visualItemsKey: 'guides.sparkle.macos.step1.visualItems',
          ctaLabelKey: 'guides.sparkle.macos.step1.ctaLabel',
        },
        {
          tone: 'connect',
          titleKey: 'guides.sparkle.macos.step2.title',
          descriptionKey: 'guides.sparkle.macos.step2.description',
          helperKey: 'guides.sparkle.macos.step2.helper',
          visualLabel: 'Policy group',
          visualLabelKey: 'guides.sparkle.macos.step2.visualLabel',
          visualItemsKey: 'guides.sparkle.macos.step2.visualItems',
          ctaLabelKey: 'guides.sparkle.macos.step2.ctaLabel',
        },
        {
          tone: 'connect',
          titleKey: 'guides.sparkle.macos.step3.title',
          descriptionKey: 'guides.sparkle.macos.step3.description',
          helperKey: 'guides.sparkle.macos.step3.helper',
          visualLabel: 'Connection toggle',
          visualLabelKey: 'guides.sparkle.macos.step3.visualLabel',
          visualItemsKey: 'guides.sparkle.macos.step3.visualItems',
          ctaLabelKey: 'guides.sparkle.macos.step3.ctaLabel',
        },
      ],
    },
    linux: {
      recommendedFormat: 'clash',
      noteKey: 'guides.sparkle.linux.note',
      steps: [
        {
          tone: 'launch',
          titleKey: 'guides.sparkle.linux.step0.title',
          descriptionKey: 'guides.sparkle.linux.step0.description',
          helperKey: 'guides.sparkle.linux.step0.helper',
          visualLabel: 'Subscription entry',
          visualLabelKey: 'guides.sparkle.linux.step0.visualLabel',
          visualItemsKey: 'guides.sparkle.linux.step0.visualItems',
          ctaLabelKey: 'guides.sparkle.linux.step0.ctaLabel',
        },
        {
          tone: 'import',
          titleKey: 'guides.sparkle.linux.step1.title',
          descriptionKey: 'guides.sparkle.linux.step1.description',
          helperKey: 'guides.sparkle.linux.step1.helper',
          visualLabel: 'Remote import',
          visualLabelKey: 'guides.sparkle.linux.step1.visualLabel',
          visualItemsKey: 'guides.sparkle.linux.step1.visualItems',
          ctaLabelKey: 'guides.sparkle.linux.step1.ctaLabel',
        },
        {
          tone: 'connect',
          titleKey: 'guides.sparkle.linux.step2.title',
          descriptionKey: 'guides.sparkle.linux.step2.description',
          helperKey: 'guides.sparkle.linux.step2.helper',
          visualLabel: 'Policy group',
          visualLabelKey: 'guides.sparkle.linux.step2.visualLabel',
          visualItemsKey: 'guides.sparkle.linux.step2.visualItems',
          ctaLabelKey: 'guides.sparkle.linux.step2.ctaLabel',
        },
        {
          tone: 'connect',
          titleKey: 'guides.sparkle.linux.step3.title',
          descriptionKey: 'guides.sparkle.linux.step3.description',
          helperKey: 'guides.sparkle.linux.step3.helper',
          visualLabel: 'Connection toggle',
          visualLabelKey: 'guides.sparkle.linux.step3.visualLabel',
          visualItemsKey: 'guides.sparkle.linux.step3.visualItems',
          ctaLabelKey: 'guides.sparkle.linux.step3.ctaLabel',
        },
      ],
    },
  },
};
