import type { ClientGuideDef } from '../types';
import {
  V2RAYN_GUIDE_SOURCE_URL,
  V2RAYN_WINDOWS_SCREENSHOTS,
  V2RAYN_LINUX_GUIDE_SOURCE_URL,
  V2RAYN_LINUX_SCREENSHOTS,
} from '../../SubscriptionTabData';

export const v2rayNGuide: ClientGuideDef = {
  byPlatform: {
    windows: {
      recommendedFormat: 'universal',
      noteKey: 'guides.v2rayN.windows.note',
      sourceLabelKey: 'guides.v2rayN.windows.sourceLabel',
      sourceUrl: V2RAYN_GUIDE_SOURCE_URL,
      steps: [
        {
          tone: 'launch',
          titleKey: 'guides.v2rayN.windows.step0.title',
          descriptionKey: 'guides.v2rayN.windows.step0.description',
          helperKey: 'guides.v2rayN.windows.step0.helper',
          visualLabel: 'Subscription group',
          visualLabelKey: 'guides.v2rayN.windows.step0.visualLabel',
          visualItemsKey: 'guides.v2rayN.windows.step0.visualItems',
          ctaLabelKey: 'guides.v2rayN.windows.step0.ctaLabel',
          screenshot: {
            src: V2RAYN_WINDOWS_SCREENSHOTS.subscriptionMenu,
            altKey: 'guides.v2rayN.windows.step0.screenshotAlt',
          },
        },
        {
          tone: 'import',
          titleKey: 'guides.v2rayN.windows.step1.title',
          descriptionKey: 'guides.v2rayN.windows.step1.description',
          helperKey: 'guides.v2rayN.windows.step1.helper',
          visualLabel: 'Add group',
          visualLabelKey: 'guides.v2rayN.windows.step1.visualLabel',
          visualItemsKey: 'guides.v2rayN.windows.step1.visualItems',
          ctaLabelKey: 'guides.v2rayN.windows.step1.ctaLabel',
          screenshot: {
            src: V2RAYN_WINDOWS_SCREENSHOTS.addGroup,
            altKey: 'guides.v2rayN.windows.step1.screenshotAlt',
          },
        },
        {
          tone: 'import',
          titleKey: 'guides.v2rayN.windows.step2.title',
          descriptionKey: 'guides.v2rayN.windows.step2.description',
          helperKey: 'guides.v2rayN.windows.step2.helper',
          visualLabel: 'Subscription URL',
          visualLabelKey: 'guides.v2rayN.windows.step2.visualLabel',
          visualItemsKey: 'guides.v2rayN.windows.step2.visualItems',
          ctaLabelKey: 'guides.v2rayN.windows.step2.ctaLabel',
          screenshot: {
            src: V2RAYN_WINDOWS_SCREENSHOTS.pasteUrl,
            altKey: 'guides.v2rayN.windows.step2.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.v2rayN.windows.step3.title',
          descriptionKey: 'guides.v2rayN.windows.step3.description',
          helperKey: 'guides.v2rayN.windows.step3.helper',
          visualLabel: 'Refresh subscription',
          visualLabelKey: 'guides.v2rayN.windows.step3.visualLabel',
          visualItemsKey: 'guides.v2rayN.windows.step3.visualItems',
          ctaLabelKey: 'guides.v2rayN.windows.step3.ctaLabel',
          screenshot: {
            src: V2RAYN_WINDOWS_SCREENSHOTS.refreshSubscription,
            altKey: 'guides.v2rayN.windows.step3.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.v2rayN.windows.step4.title',
          descriptionKey: 'guides.v2rayN.windows.step4.description',
          helperKey: 'guides.v2rayN.windows.step4.helper',
          visualLabel: 'Select node',
          visualLabelKey: 'guides.v2rayN.windows.step4.visualLabel',
          visualItemsKey: 'guides.v2rayN.windows.step4.visualItems',
          ctaLabelKey: 'guides.v2rayN.windows.step4.ctaLabel',
          screenshot: {
            src: V2RAYN_WINDOWS_SCREENSHOTS.chooseNode,
            altKey: 'guides.v2rayN.windows.step4.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.v2rayN.windows.step5.title',
          descriptionKey: 'guides.v2rayN.windows.step5.description',
          helperKey: 'guides.v2rayN.windows.step5.helper',
          visualLabel: 'System proxy',
          visualLabelKey: 'guides.v2rayN.windows.step5.visualLabel',
          visualItemsKey: 'guides.v2rayN.windows.step5.visualItems',
          ctaLabelKey: 'guides.v2rayN.windows.step5.ctaLabel',
          screenshot: {
            src: V2RAYN_WINDOWS_SCREENSHOTS.systemProxy,
            altKey: 'guides.v2rayN.windows.step5.screenshotAlt',
          },
        },
      ],
    },
    linux: {
      recommendedFormat: 'universal',
      noteKey: 'guides.v2rayN.linux.note',
      sourceLabelKey: 'guides.v2rayN.linux.sourceLabel',
      sourceUrl: V2RAYN_LINUX_GUIDE_SOURCE_URL,
      steps: [
        {
          tone: 'launch',
          titleKey: 'guides.v2rayN.linux.step0.title',
          descriptionKey: 'guides.v2rayN.linux.step0.description',
          helperKey: 'guides.v2rayN.linux.step0.helper',
          visualLabel: 'Subscription settings',
          visualLabelKey: 'guides.v2rayN.linux.step0.visualLabel',
          visualItemsKey: 'guides.v2rayN.linux.step0.visualItems',
          ctaLabelKey: 'guides.v2rayN.linux.step0.ctaLabel',
          screenshot: {
            src: V2RAYN_LINUX_SCREENSHOTS.subscriptionGroupSettings,
            altKey: 'guides.v2rayN.linux.step0.screenshotAlt',
          },
        },
        {
          tone: 'import',
          titleKey: 'guides.v2rayN.linux.step1.title',
          descriptionKey: 'guides.v2rayN.linux.step1.description',
          helperKey: 'guides.v2rayN.linux.step1.helper',
          visualLabel: 'Fill subscription',
          visualLabelKey: 'guides.v2rayN.linux.step1.visualLabel',
          visualItemsKey: 'guides.v2rayN.linux.step1.visualItems',
          ctaLabelKey: 'guides.v2rayN.linux.step1.ctaLabel',
          screenshot: {
            src: V2RAYN_LINUX_SCREENSHOTS.subscriptionGroupSettings,
            altKey: 'guides.v2rayN.linux.step1.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.v2rayN.linux.step2.title',
          descriptionKey: 'guides.v2rayN.linux.step2.description',
          helperKey: 'guides.v2rayN.linux.step2.helper',
          visualLabel: 'Node list',
          visualLabelKey: 'guides.v2rayN.linux.step2.visualLabel',
          visualItemsKey: 'guides.v2rayN.linux.step2.visualItems',
          ctaLabelKey: 'guides.v2rayN.linux.step2.ctaLabel',
          screenshot: {
            src: V2RAYN_LINUX_SCREENSHOTS.serverList,
            altKey: 'guides.v2rayN.linux.step2.screenshotAlt',
          },
        },
        {
          tone: 'connect',
          titleKey: 'guides.v2rayN.linux.step3.title',
          descriptionKey: 'guides.v2rayN.linux.step3.description',
          helperKey: 'guides.v2rayN.linux.step3.helper',
          visualLabel: 'Connect',
          visualLabelKey: 'guides.v2rayN.linux.step3.visualLabel',
          visualItemsKey: 'guides.v2rayN.linux.step3.visualItems',
          ctaLabelKey: 'guides.v2rayN.linux.step3.ctaLabel',
          screenshot: {
            src: V2RAYN_LINUX_SCREENSHOTS.serverList,
            altKey: 'guides.v2rayN.linux.step3.screenshotAlt',
          },
        },
      ],
    },
  },
};
